CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'app') THEN
        CREATE SCHEMA app;
    END IF;
END $EF$;

CREATE TABLE app.movies (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Genre" character varying(100) NOT NULL,
    "ReleaseDate" timestamp with time zone NOT NULL,
    "Rating" numeric NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastModified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_movies" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_movies_Title" ON app.movies ("Title");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250830121225_InitialCreate', '9.0.9');

ALTER TABLE app.movies ALTER COLUMN "Rating" TYPE double precision;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250830134049_RatingChangedToDouble', '9.0.9');

CREATE TABLE app."Users" (
    "Id" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250923092409_UserEntityAdded', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250923093259_AddUserAndSeed', '9.0.9');

ALTER TABLE app."Users" DROP CONSTRAINT "PK_Users";

ALTER TABLE app."Users" RENAME TO "AspNetUsers";

ALTER TABLE app."AspNetUsers" ALTER COLUMN "UserName" TYPE character varying(256);

ALTER TABLE app."AspNetUsers" ALTER COLUMN "NormalizedUserName" TYPE character varying(256);

ALTER TABLE app."AspNetUsers" ALTER COLUMN "NormalizedEmail" TYPE character varying(256);

ALTER TABLE app."AspNetUsers" ALTER COLUMN "Email" TYPE character varying(256);

ALTER TABLE app."AspNetUsers" ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");

CREATE TABLE app."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE app."AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE app."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE app."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE app."AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES app."AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE app."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES app."AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "EmailIndex" ON app."AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON app."AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON app."AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON app."AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON app."AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON app."AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON app."AspNetUserRoles" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250923115310_UserUpdateEF', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250923121513_InitialWithIdentity', '9.0.9');

ALTER TABLE app."AspNetUsers" ADD "Role" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250925115430_UserRoleAdded', '9.0.9');

ALTER TABLE app."AspNetUsers" ALTER COLUMN "Role" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250925120358_UserRolesFixAdd', '9.0.9');

ALTER TABLE app."AspNetUsers" DROP COLUMN "Role";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250925133144_UserRolesDelete', '9.0.9');

CREATE TABLE app."RefreshToken" (
    "ApplicationUserId" text NOT NULL,
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "Expires" timestamp with time zone NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Revoked" timestamp with time zone,
    CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("ApplicationUserId", "Id"),
    CONSTRAINT "FK_RefreshToken_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES app."AspNetUsers" ("Id") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250929120807_RefrshTokensAdded', '9.0.9');

CREATE TABLE app."Customer" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_Customer" PRIMARY KEY ("Id")
);

CREATE TABLE app."Product" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_Product" PRIMARY KEY ("Id")
);

CREATE TABLE app."Tag" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Tag" PRIMARY KEY ("Id")
);

CREATE TABLE app.customer_profiles (
    "Id" uuid NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "ShippingAddress" character varying(500) NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "CustomerId" uuid NOT NULL,
    CONSTRAINT "PK_customer_profiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_customer_profiles_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES app."Customer" ("Id") ON DELETE CASCADE
);

CREATE TABLE app.orders (
    "Id" uuid NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "CustomerId" uuid NOT NULL,
    CONSTRAINT "PK_orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_orders_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES app."Customer" ("Id") ON DELETE RESTRICT
);

CREATE TABLE app.product_tags (
    "ProductsId" uuid NOT NULL,
    "TagsId" uuid NOT NULL,
    CONSTRAINT "PK_product_tags" PRIMARY KEY ("ProductsId", "TagsId"),
    CONSTRAINT "FK_product_tags_Product_ProductsId" FOREIGN KEY ("ProductsId") REFERENCES app."Product" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_product_tags_Tag_TagsId" FOREIGN KEY ("TagsId") REFERENCES app."Tag" ("Id") ON DELETE CASCADE
);

CREATE TABLE app.order_items (
    "OrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Discount" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_order_items" PRIMARY KEY ("OrderId", "ProductId"),
    CONSTRAINT "FK_order_items_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES app."Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_order_items_orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES app.orders ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_customer_profiles_CustomerId" ON app.customer_profiles ("CustomerId");

CREATE INDEX "IX_order_items_ProductId" ON app.order_items ("ProductId");

CREATE INDEX "IX_orders_CustomerId" ON app.orders ("CustomerId");

CREATE INDEX "IX_product_tags_TagsId" ON app.product_tags ("TagsId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260216140637_AddEntitites_Order_Product_Customer_Tag_OrderItems', '9.0.9');

CREATE UNIQUE INDEX "IX_Customer_Name" ON app."Customer" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217101626_UpdateColumnCustomerNameIsUnique', '9.0.9');

COMMIT;

